version: "3.8"
services:
  database:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123
      - name
    ports:
      - "1433:1433"
    expose:
      - "1433"
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
  smtp:
    container_name: smtp_server
    image: rnwood/smtp4dev
    ports:
      - 2525:2525
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 5000:80
  emails_worker:
    container_name: emails_worker
    build: ./backend/ReservationSystem.EmailsWorker
    ports:
      - 6000:80
